---

- name: Make sure necessary packages are installed
  package:
    name:
      - which
      - unzip
      - tar
    state: present

- name: Create Jetty group
  group:
    name: "{{ jetty_group }}"
  tags: ['jetty']

- name: Add Jetty User
  user:
    name: "{{ jetty_user }}"
    group: "{{ jetty_group }}"
    create_home: False
    home: "{{ jetty_home }}"
    shell: /usr/sbin/nologin
  tags: ['jetty']

- name: Make sure jetty_home exists
  file:
    path: "{{ jetty_home }}"
    state: directory

- name: Copy Jetty distribution files
  copy:
    src: "{{ role_path }}/files/jetty-distribution-{{ jetty_version }}.tar.gz"
    dest: "{{ jetty_home }}"
  tags: ['jetty']

- name: Unzip Jetty distribution files
  unarchive:
    src: "{{ jetty_home }}/jetty-distribution-{{ jetty_version }}.tar.gz"
    dest: "{{ jetty_home }}"
    extra_opts:
      - --strip-components=1
    remote_src: true
    owner: "{{ jetty_user }}"
    group: "{{ jetty_group }}"
  tags: ['jetty']

- name: Install Jetty (sysv)
  file:
    src: "{{ jetty_home }}/bin/jetty.sh"
    dest: "/etc/init.d/jetty"
    state: link
  when: ansible_facts.service_mgr == 'sysvinit'
  tags: ['jetty', 'sysv', 'service']

- name: Install Jetty (systemd)
  template:
    src: jetty.service.j2
    dest: /etc/systemd/system/jetty.service
    owner: "{{ jetty_user }}"
    group: "{{ jetty_group }}"
    mode: 00750
  when: ansible_facts.service_mgr == 'systemd'
  tags: ['jetty', 'systemd', 'service']

- name: Enable and Start Jetty
  service:
    name: jetty
    enabled: yes
    state: started
  environment:
    JETTY_HOME: "{{ jetty_home }}"
  tags: ['jetty', 'service']
