---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    # image: centos:7
    image: centos/systemd
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
    options:
      c: molecule/default/ansible-lint.yml
verifier:
  name: testinfra
  lint:
    name: flake8
