---
- name: geerlingguy.java
  version: 1.9.5
  when: "ansible_os_family == 'RedHat'"
  java_packages:
    - java-1.8.0-openjdk
  java_home: /etc/alternatives/jre

- src: geerlingguy.repo-epel
  version: "1.2.4"
